# Generated by Django 3.2 on 2022-12-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='country_code',
            new_name='country',
        ),
    ]
